eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: service-zuul
  zipkin:
   base-url: http://127.0.0.1:9411
zuul:
  routes:
    api-a:
      path: /api-ribbon/**
      serviceId: SERVICE-RIBBON
    api-b:
      path: /api-feign/**
      serviceId: SERVICE-FEIGN