eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
server:
  port: 8765
spring:
  application:
    name: service-feign
    
#Feign是自带断路器（Hystrix）的，在D版本的Spring Cloud中，它没有默认打开。需要在配置文件中配置打开它 
feign:
 hystrix:
  enabled: true