server:
  port: 8770
  
spring:
 #zipkin:
  #base-url: http://127.0.0.1:9411#服务链路追踪
  
 application:
  name: service-uc-feign

eureka:
 instance:
  instance-id: ${spring.application.name}:${server.port}
  prefer-ip-address: true                       # 设置微服务调用地址为IP优先（缺省为false）
  lease-renewal-interval-in-seconds: 5          # 心跳时间，即服务续约间隔时间（缺省为30s）
  lease-expiration-duration-in-seconds: 15      # 发呆时间，即服务续约到期时间（缺省为90s）
 client:
  healthcheck:
   enabled: true                                # 开启健康检查（依赖spring-boot-starter-actuator）
  serviceUrl:
   defaultZone: http://127.0.0.1:8761/eureka/
   
   
#Feign是自带断路器（Hystrix）的，在D版本的Spring Cloud中，它没有默认打开。需要在配置文件中配置打开它 
feign:
 hystrix:
  enabled: true